export const images = {
  ACTIVISION: require("../assets/images/activision.png"),
  EA: require("../assets/images/ea.png"),
  EPIC_GAMES: require("../assets/images/epic_games.png"),
  GAME_PACK: require("../assets/images/game_pack.png"),
  PLAYSTATION: require("../assets/images/playstation.png"),
  SEGA: require("../assets/images/sega.png"),
  SPACE_GAME: require("../assets/images/space_game.png"),
  XBOX: require("../assets/images/xbox.png"),
  XBOX_LOGO: require("../assets/images/xboxLogo.png"),
  WINDOWS: require("../assets/images/windows.png"),
  PS: require("../assets/images/ps5.png"),
  OVERWATCH: require("../assets/images/overwatch.png"),
  MINECRAFT: require("../assets/images/minecraft.png"),
  TERRARIA: require("../assets/images/terraria.png"),
  BACKGROUND: require("../assets/images/backgroundImage.jpeg"),
};
