export enum AppUrls {
  CATEGORIES = "categories",
  LOGOGAMES = "logogames",
  GAMECARD = "gameCards?_sort=amountStars&_order=desc",
  USERS = "users",
  SIGN_UP = "signup",
  SIGN_IN = "signin",
  LOGOUT = "logout",
  GET_ALL_USERS = "users",
  GET_GAME_CARDS = "gameCards",
  CHANGE_PASSWORD = "change-password",
  UPDATE_PROFILE_INFO = "update-profile-info",
  UPDATE_CARD_INFO = "update-card-info",
  DELETE_CARD = "delete-card",
  UPDATE_PROFILE_AVATAR = "update-profile-avatar",
}
